[build]
command = "npm run build"
publish = ".next"

[functions]
[functions.default]
code = "nhost/functions/default"

[deploy]
subdomain = "kxcevmeaguflcpdyxnsl"
region = "eu-central-1"

[hasura]
enabled = true

[auth]
enabled = true

[storage]
enabled = true 